In [18]:
# no 4
#a) #To compute the inverse of the matrix, you can use the `np.linalg.inv()` function in NumPy:


import numpy as np

# Define the matrix
matrix = np.array([[1, 0.2, 0.5], [0.2, 1, 0.8], [0.5, 0.8, 1]])

# Compute the inverse
inverse_matrix = np.linalg.inv(matrix)

print("Inverse Matrix:")
print(inverse_matrix)



#(b) To compute the determinant of the matrix, you can use the `np.linalg.det()` function in NumPy:

import numpy as np

# Define the matrix
matrix = np.array([[1, 0.2, 0.5], [0.2, 1, 0.8], [0.5, 0.8, 1]])

# Compute the determinant
determinant = np.linalg.det(matrix)

print("Determinant:", determinant)


#(c) To decompose the matrix, you can use the Cholesky decomposition method using the `np.linalg.cholesky()` function in NumPy:

import numpy as np

# Define the matrix
matrix = np.array([[1, 0.2, 0.5], [0.2, 1, 0.8], [0.5, 0.8, 1]])

# Compute the Cholesky decomposition
decomposed_matrix = np.linalg.cholesky(matrix)

print("Decomposed Matrix (Cholesky):")
print(decomposed_matrix)

# (d) Transform the matrix (matrix multiplication for demonstration)
transformation_matrix = np.array([[2, 0, 0],
                                  [0, 3, 0],
                                  [0, 0, 1]])
transformed_matrix = matrix.dot(transformation_matrix)
print("(d) Transformed matrix (matrix multiplication):\n", transformed_matrix)



Inverse Matrix:
[[ 1.56521739  0.86956522 -1.47826087]
 [ 0.86956522  3.26086957 -3.04347826]
 [-1.47826087 -3.04347826  4.17391304]]
Determinant: 0.2299999999999999
Decomposed Matrix (Cholesky):
[[1.         0.         0.        ]
 [0.2        0.9797959  0.        ]
 [0.5        0.71443451 0.48947251]]
(d) Transformed matrix (matrix multiplication):
 [[2.  0.6 0.5]
 [0.4 3.  0.8]
 [1.  2.4 1. ]]


In [16]:
#NO 5
#Write a python program to solve three linear equations using matrices. You can use the numpy library for matrix operation

import numpy as np

def solve_linear_equations(coefficients, constants):
    A = np.array(coefficients)
    B = np.array(constants)
    
    # Use numpy's linear algebra solver to find the solution
    try:
        solution = np.linalg.solve(A, B)
        return solution
    except np.linalg.LinAlgError:

        return None

# Example system of equations:
# 7x + 8y - z  = 8
# -3x - y + 2z = -11
# -11x + y + 3z = -4

coefficients = [[7, 8, -1],
                [-3, -1, 2],
                [-11, 1, 3]]

constants = [8, -11, -4]

solution = solve_linear_equations(coefficients, constants)

if solution is not None:
    print("Solution:")
    print("x =", solution[0])
    print("y =", solution[1])
    print("z =", solution[2])
else:
    print("The system of equations has no unique solution.")

Solution:
x = -1.4000000000000001
y = 1.36
z = -6.920000000000001
